### ISSUE TITLE
Enable Pagination

### ISSUE THREAD

**Issue by chad-g-adams** [cised-ca/social-enterprise-directory#10]
To get release 1 out quicker, it was decided to drop pagination for the time being.  Pagination was essentially disabled (by setting default count to 500) by this commit:
https://github.com/cised-ca/social-enterprise-directory/commit/48592471af1ab292007278294810dbd19edcbc99

This should be reverted to something smaller once the front end is ready for pagination.

**Comment by chimo** [comment]
Found this potential candidate for the frontend: https://github.com/AdeleD/react-paginate

**Comment by chad-g-adams** [comment]
Closed by #44 and #45
