### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by chimo** [cised-ca/social-enterprise-directory#2]
Do you think we should have versioning in the API URLs so we can ship breaking changes wthout affecting clients?

For example:
`/api/v1/enterprise/:id`
`/api/latest/enterprise/:id`

And maybe URLs without versions are aliases to `latest` ?
`/api/enterprise/:id` = `/api/latest/enterprise/:id`

**Comment by chad-g-adams** [comment]
Good idea, let's put the version in the path.
I would avoid exposing any latest/alias endpoint though, as we wouldn't want any clients using those if the goal is to ship changes without breaking clients

**Comment by chimo** [comment]
Works for me!

**Comment by chad-g-adams** [comment]
Done.  As the API evolves, each version will have its own swagger definition file.

**Comment by chimo** [comment]
Well done :D
