### ISSUE TITLE
Publish Swagger documentation

### ISSUE THREAD

**Issue by chad-g-adams** [cised-ca/social-enterprise-directory#3]
It is possible to generate static html of the API documentation using swagger-codegen:
https://github.com/swagger-api/swagger-codegen

Not a high priority by any stretch, but it would be cool to auto-generate this on every commit and publish the html to the Github Pages site for this project which could be used as a reference for any developers trying to integrate with our API.

**Comment by chimo** [comment]
+1

**Comment by nsieber** [comment]
+1

**Comment by chad-g-adams** [comment]
API documentation is now available on swaggerhub:
https://app.swaggerhub.com/api/chad.adams/SocialEnterpriseDirectory/1

I've updated the README with the link.
