### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by chad-g-adams** [cised-ca/social-enterprise-directory#4]
The backend should serve the logos as static files.

TBD: How will the logos get there? New API?

Twitter uses API to upload images:
https://dev.twitter.com/rest/reference/post/media/upload

**Comment by chad-g-adams** [comment]
Alternatively, the logos can be stored in Mongo. 

I would imagine we would want a URL like:
/api/enterprise/{id}/logo

**Comment by nsieber** [comment]
Store in Mongo seems more straight forward for the time being.

**Comment by chad-g-adams** [comment]
Done in Release 1. Will raise separate issue to expose api's for logo creation/modification.
