### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chimo** [cised-ca/social-enterprise-directory#7]
We need to decide which license this code is avaialble under.

Myself, I'd prefer a Free license over an Open one, but this is worth discussing.

**Comment by chad-g-adams** [comment]
Free works for me. Any one in particular you were thinking about?

**Comment by nsieber** [comment]
Another +1 for free. There's too many for me to have an opinion on which one though. :)

**Comment by chimo** [comment]
When it comes to copyleft/free licensing and server-side software, the usual choice is the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html).

It's basically the GPL with an additional clause ensuring software freedom for software that's not distributed to users (as such is the case with server-side software).

[The MongoDB core is AGPL](http://blog.mongodb.org/post/103832439/the-agpl), for example.

**Comment by chad-g-adams** [comment]
AGPL is ok with me

**Comment by nsieber** [comment]
+1 AGPL looks like a good fit
