### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by chad-g-adams** [cised-ca/social-enterprise-directory#8]
I would really like to get some tests in place early on, but I'm not familiar with any of the javascript testing frameworks so it would take some research on my part for me to pick one subjectively.  Swagger does bootstrap some skeleton test framework into the project, but that might not necessarily be the best choice.  Does any one have any knowledge/suggestions?  

At this point I am non-opinionated, and would probably just run with the Swagger selection if left to my own devices..

**Comment by chad-g-adams** [comment]
Swagger is using `supertest` and `should`

**Comment by nsieber** [comment]
I've never heard of these myself. 

I've only use Qunit which is more frontend oriented. 

The names that are usually thrown around are Mocha, Jasmine, and Karma. But apparently they all come with some baggage so maybe we just go with Swagger's defaults.

**Comment by chad-g-adams** [comment]
FYI Upon further investigation, it turns out the swagger CLI is just a wrapper around mocha, so I have proceeded with that.
